[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM15
monitor_port = COM15
monitor_speed = 115200

lib_deps =
  https://github.com/mobizt/Firebase-ESP-Client.git
